### PR TITLE
binding-http: vocabulary alignment 

### PR DESCRIPTION
**Pull request by fillobotto**
See https://github.com/eclipse/thingweb.node-wot/issues/606

### CODE REVIEW

**Comment by fillobotto** [comment]
Problem is oauth2 client library which seems not to accept "client" as a valid grant type.
Here I found some clue: https://github.com/mulesoft-labs/js-client-oauth2/blob/68d2a71565641d321148798d7df9d78a3182e584/src/client-oauth2.js#L542

**Review by relu91 — CHANGES_REQUESTED** [review]
You should use `client` as a configuration term from the TD but when you send through an HTTP request use `client_credentials`

**Comment by fillobotto** [comment]
> Problem is oauth2 client library which seems not to accept "client" as a valid grant type. Here I found some clue: https://github.com/mulesoft-labs/js-client-oauth2/blob/68d2a71565641d321148798d7df9d78a3182e584/src/client-oauth2.js#L542

@relu91 so, keeping in mind the above problem, what I have to do is...checking if flow name is "client_credential" and then convert it to "client" right before passing it to oauth? I don't kinda like it :/

**Comment by relu91** [comment]
> @relu91 so, keeping in mind the above problem, what I have to do is...checking if flow name is "client_credential" and then convert it to "client" right before passing it to oauth? I don't kinda like it :/

It should be the opposite :) otherwise, we can bring this to the wg and change TD vocabulary to have `client_credentials` instead of `client`

**Review by relu91 — APPROVED** [review]

**Comment by relu91** [comment]
Good to go thanks!

**Pull request merged**
